Fix distroVersion if unknown version in VMWARE
 File "/opt/netbox-sync/module/sources/vmware/connection.py", line 2200, in add_virtual_machine

detailed_data_dict.get("distroVersion") not in platform:

TypeError: 'in <string>' requires string as left operand, not NoneType 

Fixes this error, this seemed to be when a OS version is not known in VMWare.